import { z } from "zod";

/**
 * Validates a transcript before persisting it from Vapi's end-of-call-report webhook.
 *
 * Deliberately lenient on the free-text/URL fields (summary, transcript_text, recording_url):
 * this data is only ever machine-generated by Vapi, never user input to sanitize against, and
 * losing an entire call transcript because e.g. `recording_url` came back in an unexpected
 * format would be a worse outcome than storing it as-is. `vapi_call_id` is the one field that
 * matters for correctness (it's what makes the upsert idempotent), so that stays required.
 */
export const createTranscriptSchema = z
  .object({
    patient_id: z.string().uuid().nullable(),
    vapi_call_id: z.string().trim().min(1).max(100),
    summary: z.string().nullable().optional(),
    transcript_text: z.string().nullable().optional(),
    recording_url: z.string().nullable().optional(),
    duration_seconds: z.number().int().nonnegative().nullable().optional(),
  })
  .strict();
